//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aufgabe
    {
        public Aufgabe()
        {
            this.Ergebnisse = new HashSet<Ergebnis>();
        }
    
        public int Id { get; set; }
        public int ArbeitId { get; set; }
        public int LfdNr { get; set; }
        public float MaxPunkte { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Ergebnis> Ergebnisse { get; set; }
        public virtual Arbeit Arbeit { get; set; }
    }
}
