//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bewertungsschema
    {
        public Bewertungsschema()
        {
            this.Prozentbereiche = new HashSet<Prozentbereich>();
            this.Arbeiten = new HashSet<Arbeit>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Prozentbereich> Prozentbereiche { get; set; }
        public virtual ICollection<Arbeit> Arbeiten { get; set; }
    }
}
