//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public Curriculum()
        {
            this.Reihen = new HashSet<Reihe>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlassenstufeId { get; set; }
        public string Bezeichnung { get; set; }
        public int JahrtypId { get; set; }
        public int HalbjahrtypId { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
        public virtual ICollection<Reihe> Reihen { get; set; }
        public virtual Halbjahrtyp Halbjahrtyp { get; set; }
    }
}
