//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dateityp
    {
        public Dateityp()
        {
            this.Dateiverweis = new HashSet<Dateiverweis>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Kürzel { get; set; }
    
        public virtual ICollection<Dateiverweis> Dateiverweis { get; set; }
    }
}
