//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dateityp
    {
        public Dateityp()
        {
            this.Dateiverweis = new HashSet<Dateiverweis>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Kürzel { get; set; }
    
        public virtual ICollection<Dateiverweis> Dateiverweis { get; set; }
    }
}
