//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ergebnis
    {
        public int Id { get; set; }
        public int AufgabeId { get; set; }
        public int SchülereintragId { get; set; }
        public Nullable<float> Punktzahl { get; set; }
    
        public virtual Aufgabe Aufgabe { get; set; }
        public virtual Schülereintrag Schülereintrag { get; set; }
    }
}
