//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fach
    {
        public Fach()
        {
            this.Stundenentwurf = new HashSet<Stundenentwurf>();
            this.Modul = new HashSet<Modul>();
            this.Stundenplaneintrag = new HashSet<Stundenplaneintrag>();
            this.Jahresplan = new HashSet<Jahresplan>();
            this.Curriculum = new HashSet<Curriculum>();
            this.Fachstundenanzahl = new HashSet<Fachstundenanzahl>();
            this.Arbeiten = new HashSet<Arbeit>();
            this.Schülerlisten = new HashSet<Schülerliste>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Farbe { get; set; }
    
        public virtual ICollection<Stundenentwurf> Stundenentwurf { get; set; }
        public virtual ICollection<Modul> Modul { get; set; }
        public virtual ICollection<Stundenplaneintrag> Stundenplaneintrag { get; set; }
        public virtual ICollection<Jahresplan> Jahresplan { get; set; }
        public virtual ICollection<Curriculum> Curriculum { get; set; }
        public virtual ICollection<Fachstundenanzahl> Fachstundenanzahl { get; set; }
        public virtual ICollection<Arbeit> Arbeiten { get; set; }
        public virtual ICollection<Schülerliste> Schülerlisten { get; set; }
    }
}
