//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fachstundenanzahl
    {
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlassenstufeId { get; set; }
        public int Stundenzahl { get; set; }
        public int Teilungsstundenzahl { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
    }
}
