//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fachstundenanzahl
    {
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlassenstufeId { get; set; }
        public int Stundenzahl { get; set; }
        public int Teilungsstundenzahl { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
    }
}
