//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ferien
    {
        public int Id { get; set; }
        public int JahrtypId { get; set; }
        public string Bezeichnung { get; set; }
        public System.DateTime ErsterFerientag { get; set; }
        public System.DateTime LetzterFerientag { get; set; }
    
        public virtual Jahrtyp Jahrtyp { get; set; }
    }
}
