//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halbjahrtyp
    {
        public Halbjahrtyp()
        {
            this.Schulhalbjahr = new HashSet<Halbjahresplan>();
            this.Stundenplan = new HashSet<Stundenplan>();
            this.Arbeit = new HashSet<Arbeit>();
            this.Schülerliste = new HashSet<Schülerliste>();
            this.Curricula = new HashSet<Curriculum>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int HalbjahrIndex { get; set; }
    
        public virtual ICollection<Halbjahresplan> Schulhalbjahr { get; set; }
        public virtual ICollection<Stundenplan> Stundenplan { get; set; }
        public virtual ICollection<Arbeit> Arbeit { get; set; }
        public virtual ICollection<Schülerliste> Schülerliste { get; set; }
        public virtual ICollection<Curriculum> Curricula { get; set; }
    }
}
