//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halbjahresplan
    {
        public Halbjahresplan()
        {
            this.Monatspläne = new HashSet<Monatsplan>();
        }
    
        public int Id { get; set; }
        public int JahresplanId { get; set; }
        public int HalbjahrtypId { get; set; }
    
        public virtual Halbjahrtyp Halbjahrtyp { get; set; }
        public virtual ICollection<Monatsplan> Monatspläne { get; set; }
        public virtual Jahresplan Jahresplan { get; set; }
    }
}
