//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halbjahrtyp
    {
        public Halbjahrtyp()
        {
            this.Schulhalbjahr = new HashSet<Halbjahresplan>();
            this.Stundenplan = new HashSet<Stundenplan>();
            this.Arbeit = new HashSet<Arbeit>();
            this.Curricula = new HashSet<Curriculum>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int HalbjahrIndex { get; set; }
    
        public virtual ICollection<Halbjahresplan> Schulhalbjahr { get; set; }
        public virtual ICollection<Stundenplan> Stundenplan { get; set; }
        public virtual ICollection<Arbeit> Arbeit { get; set; }
        public virtual ICollection<Curriculum> Curricula { get; set; }
    }
}
