//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Halbjahresplan
    {
        public Halbjahresplan()
        {
            this.Monatspläne = new HashSet<Monatsplan>();
        }
    
        public int Id { get; set; }
        public int JahresplanId { get; set; }
        public int HalbjahrtypId { get; set; }
    
        public virtual Halbjahrtyp Halbjahrtyp { get; set; }
        public virtual ICollection<Monatsplan> Monatspläne { get; set; }
        public virtual Jahresplan Jahresplan { get; set; }
    }
}
