//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hausaufgabe
    {
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public string Bezeichnung { get; set; }
        public bool IstNachgereicht { get; set; }
        public int SchülereintragId { get; set; }
    
        public virtual Schülereintrag Schülereintrag { get; set; }
    }
}
