//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jahresplan
    {
        public Jahresplan()
        {
            this.Halbjahrespläne = new HashSet<Halbjahresplan>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlasseId { get; set; }
        public int JahrtypId { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Klasse Klasse { get; set; }
        public virtual ICollection<Halbjahresplan> Halbjahrespläne { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
    }
}
