//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jahrgangsstufe
    {
        public Jahrgangsstufe()
        {
            this.Stundenentwurf = new HashSet<Stundenentwurf>();
            this.Klassenstufen = new HashSet<Klassenstufe>();
            this.Module = new HashSet<Modul>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Bepunktungstyp { get; set; }
    
        public virtual ICollection<Stundenentwurf> Stundenentwurf { get; set; }
        public virtual ICollection<Klassenstufe> Klassenstufen { get; set; }
        public virtual ICollection<Modul> Module { get; set; }
    }
}
