//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klassenstufe
    {
        public Klassenstufe()
        {
            this.Fachstundenanzahl = new HashSet<Fachstundenanzahl>();
            this.Curriculum = new HashSet<Curriculum>();
            this.Klassen = new HashSet<Klasse>();
        }
    
        public int Id { get; set; }
        public int JahrgangsstufeId { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
        public virtual ICollection<Fachstundenanzahl> Fachstundenanzahl { get; set; }
        public virtual ICollection<Curriculum> Curriculum { get; set; }
        public virtual ICollection<Klasse> Klassen { get; set; }
    }
}
