//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasse
    {
        public Klasse()
        {
            this.Stundenplaneintrag = new HashSet<Stundenplaneintrag>();
            this.Jahresplan = new HashSet<Jahresplan>();
            this.BetroffeneKlasse = new HashSet<BetroffeneKlasse>();
            this.Arbeit = new HashSet<Arbeit>();
            this.Schülerlisten = new HashSet<Schülerliste>();
        }
    
        public int Id { get; set; }
        public int KlassenstufeId { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Stundenplaneintrag> Stundenplaneintrag { get; set; }
        public virtual ICollection<Jahresplan> Jahresplan { get; set; }
        public virtual ICollection<BetroffeneKlasse> BetroffeneKlasse { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
        public virtual ICollection<Arbeit> Arbeit { get; set; }
        public virtual ICollection<Schülerliste> Schülerlisten { get; set; }
    }
}
