//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klasse
    {
        public Klasse()
        {
            this.Stundenplaneintrag = new HashSet<Stundenplaneintrag>();
            this.Jahresplan = new HashSet<Jahresplan>();
            this.BetroffeneKlasse = new HashSet<BetroffeneKlasse>();
            this.Arbeit = new HashSet<Arbeit>();
            this.Schülerliste = new HashSet<Schülerliste>();
        }
    
        public int Id { get; set; }
        public int KlassenstufeId { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Stundenplaneintrag> Stundenplaneintrag { get; set; }
        public virtual ICollection<Jahresplan> Jahresplan { get; set; }
        public virtual ICollection<BetroffeneKlasse> BetroffeneKlasse { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
        public virtual ICollection<Arbeit> Arbeit { get; set; }
        public virtual ICollection<Schülerliste> Schülerliste { get; set; }
    }
}
