//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modul
    {
        public Modul()
        {
            this.Bausteine = "";
            this.Stundenentwurf = new HashSet<Stundenentwurf>();
            this.Reihen = new HashSet<Reihe>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public string Bezeichnung { get; set; }
        public int JahrgangsstufeId { get; set; }
        public string Bausteine { get; set; }
        public int Stundenbedarf { get; set; }
    
        public virtual ICollection<Stundenentwurf> Stundenentwurf { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual ICollection<Reihe> Reihen { get; set; }
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
    }
}
