//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monatsplan
    {
        public Monatsplan()
        {
            this.Tagespläne = new HashSet<Tagesplan>();
        }
    
        public int Id { get; set; }
        public int HalbjahresplanId { get; set; }
        public int MonatstypId { get; set; }
    
        public virtual Monatstyp Monatstyp { get; set; }
        public virtual Halbjahresplan Halbjahresplan { get; set; }
        public virtual ICollection<Tagesplan> Tagespläne { get; set; }
    }
}
