//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monatstyp
    {
        public Monatstyp()
        {
            this.Kalendermonat = new HashSet<Monatsplan>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int MonatIndex { get; set; }
    
        public virtual ICollection<Monatsplan> Kalendermonat { get; set; }
    }
}
