//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public Note()
        {
            this.NotenTermintyp = "Einzeln";
        }
    
        public int Id { get; set; }
        public int SchülereintragId { get; set; }
        public int ZensurId { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> ArbeitId { get; set; }
        public int Wichtung { get; set; }
        public bool IstSchriftlich { get; set; }
        public string Bezeichnung { get; set; }
        public string Notentyp { get; set; }
        public string NotenTermintyp { get; set; }
    
        public virtual Zensur Zensur { get; set; }
        public virtual Schülereintrag Schülereintrag { get; set; }
        public virtual Arbeit Arbeit { get; set; }
    }
}
