//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotenWichtung
    {
        public NotenWichtung()
        {
            this.Schülerlisten = new HashSet<Schülerliste>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public float MündlichQualität { get; set; }
        public float MündlichQuantität { get; set; }
        public float MündlichSonstige { get; set; }
        public float MündlichGesamt { get; set; }
        public float SchriftlichKlassenarbeit { get; set; }
        public float SchriftlichSonstige { get; set; }
        public float SchriftlichGesamt { get; set; }
    
        public virtual ICollection<Schülerliste> Schülerlisten { get; set; }
    }
}
