//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notentendenz
    {
        public int Id { get; set; }
        public int TendenztypId { get; set; }
        public System.DateTime Datum { get; set; }
        public int TendenzId { get; set; }
        public string Bezeichnung { get; set; }
        public int SchülereintragId { get; set; }
    
        public virtual Tendenz Tendenz { get; set; }
        public virtual Tendenztyp Tendenztyp { get; set; }
        public virtual Schülereintrag Schülereintrag { get; set; }
    }
}
