//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotenWichtung
    {
        public NotenWichtung()
        {
            this.Schülerlisten = new HashSet<Schülerliste>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public float MündlichQualität { get; set; }
        public float MündlichQuantität { get; set; }
        public float MündlichSonstige { get; set; }
        public float MündlichGesamt { get; set; }
        public float SchriftlichKlassenarbeit { get; set; }
        public float SchriftlichSonstige { get; set; }
        public float SchriftlichGesamt { get; set; }
    
        public virtual ICollection<Schülerliste> Schülerlisten { get; set; }
    }
}
