//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public Phase()
        {
            this.AbfolgeIndex = 0;
        }
    
        public int Id { get; set; }
        public int StundenentwurfId { get; set; }
        public int Zeit { get; set; }
        public int MediumId { get; set; }
        public int SozialformId { get; set; }
        public string Inhalt { get; set; }
        public int AbfolgeIndex { get; set; }
    
        public virtual Stundenentwurf Stundenentwurf { get; set; }
        public virtual Sozialform Sozialform { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
