//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prozentbereich
    {
        public int Id { get; set; }
        public int ZensurId { get; set; }
        public float VonProzent { get; set; }
        public float BisProzent { get; set; }
        public int BewertungsschemaId { get; set; }
    
        public virtual Zensur Zensur { get; set; }
        public virtual Bewertungsschema Bewertungsschema { get; set; }
    }
}
