//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raum
    {
        public Raum()
        {
            this.Raumpläne = new HashSet<Raumplan>();
            this.Stundenplaneinträge = new HashSet<Stundenplaneintrag>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Raumplan> Raumpläne { get; set; }
        public virtual ICollection<Stundenplaneintrag> Stundenplaneinträge { get; set; }
    }
}
