//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raumplan
    {
        public Raumplan()
        {
            this.Sitzpläne = new HashSet<Sitzplan>();
            this.Sitzplätze = new HashSet<Sitzplatz>();
        }
    
        public int Id { get; set; }
        public int RaumId { get; set; }
        public string Bezeichnung { get; set; }
        public byte[] Grundriss { get; set; }
    
        public virtual Raum Raum { get; set; }
        public virtual ICollection<Sitzplan> Sitzpläne { get; set; }
        public virtual ICollection<Sitzplatz> Sitzplätze { get; set; }
    }
}
