//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raumplan
    {
        public Raumplan()
        {
            this.Sitzpläne = new HashSet<Sitzplan>();
            this.Sitzplätze = new HashSet<Sitzplatz>();
        }
    
        public int Id { get; set; }
        public int RaumId { get; set; }
        public string Bezeichnung { get; set; }
        public byte[] Grundriss { get; set; }
    
        public virtual Raum Raum { get; set; }
        public virtual ICollection<Sitzplan> Sitzpläne { get; set; }
        public virtual ICollection<Sitzplatz> Sitzplätze { get; set; }
    }
}
