//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raum
    {
        public Raum()
        {
            this.Raumpläne = new HashSet<Raumplan>();
            this.Stundenplaneinträge = new HashSet<Stundenplaneintrag>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Raumplan> Raumpläne { get; set; }
        public virtual ICollection<Stundenplaneintrag> Stundenplaneinträge { get; set; }
    }
}
