//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reihe
    {
        public Reihe()
        {
            this.Sequenzen = new HashSet<Sequenz>();
        }
    
        public int Id { get; set; }
        public int ModulId { get; set; }
        public string Thema { get; set; }
        public int Stundenbedarf { get; set; }
        public int CurriculumId { get; set; }
        public int AbfolgeIndex { get; set; }
    
        public virtual Modul Modul { get; set; }
        public virtual ICollection<Sequenz> Sequenzen { get; set; }
        public virtual Curriculum Curriculum { get; set; }
    }
}
