//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schultermin : Termin
    {
        public Schultermin()
        {
            this.BetroffeneKlassen = new HashSet<BetroffeneKlasse>();
        }
    
        public int JahrtypId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual ICollection<BetroffeneKlasse> BetroffeneKlassen { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
    }
}
