//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schulwoche
    {
        public Schulwoche()
        {
            this.Schultage = new HashSet<Schultag>();
        }
    
        public int Id { get; set; }
        public int JahrtypId { get; set; }
        public System.DateTime Montagsdatum { get; set; }
    
        public virtual Jahrtyp Jahrtyp { get; set; }
        public virtual ICollection<Schultag> Schultage { get; set; }
    }
}
