//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schultag
    {
        public int Id { get; set; }
        public int SchulwocheId { get; set; }
        public int TermintypId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Schulwoche Schulwoche { get; set; }
        public virtual Termintyp Termintyp { get; set; }
    }
}
