//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schultermin : Termin
    {
        public Schultermin()
        {
            this.BetroffeneKlassen = new HashSet<BetroffeneKlasse>();
        }
    
        public int JahrtypId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual ICollection<BetroffeneKlasse> BetroffeneKlassen { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
    }
}
