//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schülereintrag
    {
        public Schülereintrag()
        {
            this.Ergebnisse = new HashSet<Ergebnis>();
            this.Noten = new HashSet<Note>();
            this.Hausaufgaben = new HashSet<Hausaufgabe>();
            this.Notentendenzen = new HashSet<Notentendenz>();
            this.Sitzplaneinträge = new HashSet<Sitzplaneintrag>();
        }
    
        public int Id { get; set; }
        public int SchülerlisteId { get; set; }
        public int PersonId { get; set; }
    
        public virtual ICollection<Ergebnis> Ergebnisse { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Note> Noten { get; set; }
        public virtual ICollection<Hausaufgabe> Hausaufgaben { get; set; }
        public virtual ICollection<Notentendenz> Notentendenzen { get; set; }
        public virtual ICollection<Sitzplaneintrag> Sitzplaneinträge { get; set; }
        public virtual Schülerliste Schülerliste { get; set; }
    }
}
