//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schülerliste
    {
        public Schülerliste()
        {
            this.Schülereinträge = new HashSet<Schülereintrag>();
            this.Sitzpläne = new HashSet<Sitzplan>();
        }
    
        public int Id { get; set; }
        public int JahrtypId { get; set; }
        public int KlasseId { get; set; }
        public int FachId { get; set; }
        public int NotenWichtungId { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
        public virtual Klasse Klasse { get; set; }
        public virtual NotenWichtung NotenWichtung { get; set; }
        public virtual ICollection<Schülereintrag> Schülereinträge { get; set; }
        public virtual ICollection<Sitzplan> Sitzpläne { get; set; }
    }
}
