//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sequenz
    {
        public Sequenz()
        {
            this.AbfolgeIndex = -1;
        }
    
        public int Id { get; set; }
        public int ReiheId { get; set; }
        public int AbfolgeIndex { get; set; }
        public int Stundenbedarf { get; set; }
        public string Thema { get; set; }
    
        public virtual Reihe Reihe { get; set; }
    }
}
