//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitzplaneintrag
    {
        public int Id { get; set; }
        public int SitzplanId { get; set; }
        public int SitzplatzId { get; set; }
        public Nullable<int> SchülereintragId { get; set; }
    
        public virtual Schülereintrag Schülereintrag { get; set; }
        public virtual Sitzplan Sitzplan { get; set; }
        public virtual Sitzplatz Sitzplatz { get; set; }
    }
}
