//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sitzplatz
    {
        public Sitzplatz()
        {
            this.Sitzplaneinträge = new HashSet<Sitzplaneintrag>();
        }
    
        public int Id { get; set; }
        public int RaumplanId { get; set; }
        public double LinksObenX { get; set; }
        public double LinksObenY { get; set; }
        public double Breite { get; set; }
        public double Höhe { get; set; }
        public double Drehwinkel { get; set; }
    
        public virtual Raumplan Raumplan { get; set; }
        public virtual ICollection<Sitzplaneintrag> Sitzplaneinträge { get; set; }
    }
}
