//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozialform
    {
        public Sozialform()
        {
            this.Phase = new HashSet<Phase>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ICollection<Phase> Phase { get; set; }
    }
}
