//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stundenentwurf
    {
        public Stundenentwurf()
        {
            this.Phasen = new HashSet<Phase>();
            this.Stunden = new HashSet<Stunde>();
            this.Dateiverweise = new HashSet<Dateiverweis>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int JahrgangsstufeId { get; set; }
        public int ModulId { get; set; }
        public string Stundenthema { get; set; }
        public bool Kopieren { get; set; }
        public bool Computer { get; set; }
        public string Hausaufgaben { get; set; }
        public string Ansagen { get; set; }
        public System.DateTime Datum { get; set; }
        public int Stundenzahl { get; set; }
    
        public virtual ICollection<Phase> Phasen { get; set; }
        public virtual Modul Modul { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual ICollection<Stunde> Stunden { get; set; }
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
        public virtual ICollection<Dateiverweis> Dateiverweise { get; set; }
    }
}
