//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stundenplaneintrag
    {
        public int Id { get; set; }
        public int StundenplanId { get; set; }
        public int ErsteUnterrichtsstundeIndex { get; set; }
        public int LetzteUnterrichtsstundeIndex { get; set; }
        public int WochentagIndex { get; set; }
        public int FachId { get; set; }
        public int KlasseId { get; set; }
        public int RaumId { get; set; }
    
        public virtual Klasse Klasse { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual Stundenplan Stundenplan { get; set; }
        public virtual Raum Raum { get; set; }
    }
}
