//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stundenplaneintrag
    {
        public int Id { get; set; }
        public int StundenplanId { get; set; }
        public int ErsteUnterrichtsstundeIndex { get; set; }
        public int LetzteUnterrichtsstundeIndex { get; set; }
        public int WochentagIndex { get; set; }
        public int FachId { get; set; }
        public int KlasseId { get; set; }
        public int RaumId { get; set; }
    
        public virtual Klasse Klasse { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual Stundenplan Stundenplan { get; set; }
        public virtual Raum Raum { get; set; }
    }
}
