//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stunde : Lerngruppentermin
    {
        public Stunde()
        {
            this.IstBenotet = false;
        }
    
        public Nullable<int> StundenentwurfId { get; set; }
        public bool IstBenotet { get; set; }
    
        public virtual Stundenentwurf Stundenentwurf { get; set; }
    }
}
