//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tagesplan
    {
        public Tagesplan()
        {
            this.Ferientag = false;
            this.Beschreibung = "";
            this.Lerngruppentermine = new HashSet<Lerngruppentermin>();
        }
    
        public int Id { get; set; }
        public int MonatsplanId { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Ferientag { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual Monatsplan Monatsplan { get; set; }
        public virtual ICollection<Lerngruppentermin> Lerngruppentermine { get; set; }
    }
}
