//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tagesplan
    {
        public Tagesplan()
        {
            this.Ferientag = false;
            this.Beschreibung = "";
            this.Lerngruppentermine = new HashSet<Lerngruppentermin>();
        }
    
        public int Id { get; set; }
        public int MonatsplanId { get; set; }
        public System.DateTime Datum { get; set; }
        public bool Ferientag { get; set; }
        public string Beschreibung { get; set; }
    
        public virtual Monatsplan Monatsplan { get; set; }
        public virtual ICollection<Lerngruppentermin> Lerngruppentermine { get; set; }
    }
}
