//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termintyp
    {
        public Termintyp()
        {
            this.Termin = new HashSet<Termin>();
            this.Schultag = new HashSet<Schultag>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Kalenderfarbe { get; set; }
    
        public virtual ICollection<Termin> Termin { get; set; }
        public virtual ICollection<Schultag> Schultag { get; set; }
    }
}
