//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unterrichtsstunde
    {
        public Unterrichtsstunde()
        {
            this.TerminErste = new HashSet<Termin>();
            this.TerminLetzte = new HashSet<Termin>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public System.TimeSpan Beginn { get; set; }
        public System.TimeSpan Ende { get; set; }
        public int Stundenindex { get; set; }
    
        public virtual ICollection<Termin> TerminErste { get; set; }
        public virtual ICollection<Termin> TerminLetzte { get; set; }
    }
}
