//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unterrichtsstunde
    {
        public Unterrichtsstunde()
        {
            this.TerminErste = new HashSet<Termin>();
            this.TerminLetzte = new HashSet<Termin>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public System.TimeSpan Beginn { get; set; }
        public System.TimeSpan Ende { get; set; }
        public int Stundenindex { get; set; }
    
        public virtual ICollection<Termin> TerminErste { get; set; }
        public virtual ICollection<Termin> TerminLetzte { get; set; }
    }
}
