//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArbeitNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArbeitNeu()
        {
            this.Aufgaben = new HashSet<AufgabeNeu>();
            this.Noten = new HashSet<NotenNeu>();
        }
    
        public int Id { get; set; }
        public int LerngruppeId { get; set; }
        public int FachId { get; set; }
        public int BewertungsschemaId { get; set; }
        public int Bepunktungstyp { get; set; }
        public string Bezeichnung { get; set; }
        public int LfdNr { get; set; }
        public System.DateTime Datum { get; set; }
        public bool IstKlausur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AufgabeNeu> Aufgaben { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotenNeu> Noten { get; set; }
        public virtual BewertungsschemataNeu Bewertungsschema { get; set; }
        public virtual FächerNeu Fach { get; set; }
        public virtual LerngruppeNeu Lerngruppe { get; set; }
    }
}
