//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AufgabeNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AufgabeNeu()
        {
            this.Ergebnisse = new HashSet<ErgebnisseNeu>();
        }
    
        public int Id { get; set; }
        public int ArbeitId { get; set; }
        public int LfdNr { get; set; }
        public double MaxPunkte { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual ArbeitNeu Arbeit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErgebnisseNeu> Ergebnisse { get; set; }
    }
}
