//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateiverweisNeu
    {
        public int Id { get; set; }
        public string Dateiname { get; set; }
        public int DateitypId { get; set; }
        public int StundeId { get; set; }
    
        public virtual DateitypNeu Dateityp { get; set; }
        public virtual StundeNeu Stunde { get; set; }
    }
}
