//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FachstundenanzahlNeu
    {
        public int Id { get; set; }
        public int FachId { get; set; }
        public int Jahrgang { get; set; }
        public int Stundenzahl { get; set; }
        public int Teilungsstundenzahl { get; set; }
    
        public virtual FachNeu Fach { get; set; }
    }
}
