//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FerienNeu
    {
        public int Id { get; set; }
        public int SchuljahrId { get; set; }
        public string Bezeichnung { get; set; }
        public System.DateTime ErsterFerientag { get; set; }
        public System.DateTime LetzterFerientag { get; set; }
    
        public virtual SchuljahrNeu Schuljahr { get; set; }
    }
}
