//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LerngruppeNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LerngruppeNeu()
        {
            this.Arbeiten = new HashSet<ArbeitNeu>();
            this.BetroffeneKlassen = new HashSet<BetroffeneKlasseNeu>();
            this.Lerngruppentermine = new HashSet<LerngruppenterminNeu>();
            this.Stundenplaneinträge = new HashSet<StundenplaneintragNeu>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int SchuljahrId { get; set; }
        public int Halbjahr { get; set; }
        public int FachId { get; set; }
        public int Jahrgang { get; set; }
        public int NotenWichtungId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArbeitNeu> Arbeiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetroffeneKlasseNeu> BetroffeneKlassen { get; set; }
        public virtual FächerNeu Fach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LerngruppenterminNeu> Lerngruppentermine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StundenplaneintragNeu> Stundenplaneinträge { get; set; }
        public virtual NotenWichtungNeu NotenWichtung { get; set; }
        public virtual SchuljahrNeu Schuljahr { get; set; }
    }
}
