//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LerngruppenterminNeu : TerminNeu
    {
        public Nullable<int> LerngruppeId { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual LerngruppeNeu Lerngruppe { get; set; }
    }
}
