//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    
    public enum Medium : int
    {
        Tafel = 0,
        Beamer = 1,
        OH = 2,
        Experiment = 3,
        Hefter = 4,
        Pause = 5,
        Buch = 6,
        Spiel = 7,
        Computer = 8,
        Film = 9,
        Arbeitsbogen = 10,
        Dokumentenkamera = 11,
        Poster = 12
    }
}
