//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleNeu()
        {
            this.Reihen = new HashSet<ReihenNeu>();
            this.Stunden = new HashSet<StundeNeu>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public string Bezeichnung { get; set; }
        public int Jahrgang { get; set; }
        public string Bausteine { get; set; }
        public int Stundenbedarf { get; set; }
    
        public virtual FächerNeu Fach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReihenNeu> Reihen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StundeNeu> Stunden { get; set; }
    }
}
