//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotenNeu
    {
        public int Id { get; set; }
        public int SchülereintragId { get; set; }
        public int ZensurId { get; set; }
        public System.DateTime Datum { get; set; }
        public int Wichtung { get; set; }
        public bool IstSchriftlich { get; set; }
        public Nullable<int> ArbeitId { get; set; }
        public string Bezeichnung { get; set; }
        public int Notentyp { get; set; }
        public Nullable<int> NotenTermintyp { get; set; }
    
        public virtual ArbeitNeu Arbeit { get; set; }
        public virtual SchülereinträgeNeu Schülereintrag { get; set; }
        public virtual ZensurenNeu Zensur { get; set; }
    }
}
