//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotentendenzNeu
    {
        public int Id { get; set; }
        public System.DateTime Datum { get; set; }
        public Tendenz Tendenz { get; set; }
        public Tendenztyp Tendenztyp { get; set; }
        public string Bezeichnung { get; set; }
        public int SchülereintragId { get; set; }
    
        public virtual SchülereintragNeu Schülereintrag { get; set; }
    }
}
