//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    
    public enum Notentyp : int
    {
        MündlichGesamt = 1,
        MündlichQualität = 2,
        MündlichQuantität = 3,
        MündlichSonstige = 4,
        MündlichStand = 5,
        SchriftlichKlassenarbeit = 6,
        SchriftlichSonstige = 7,
        SchriftlichGesamt = 8,
        SchriftlichStand = 9,
        GesamtStand = 10
    }
}
