//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProzentbereicheNeu
    {
        public int Id { get; set; }
        public int ZensurId { get; set; }
        public double VonProzent { get; set; }
        public double BisProzent { get; set; }
        public int BewertungsschemaId { get; set; }
    
        public virtual BewertungsschemataNeu Bewertungsschema { get; set; }
        public virtual ZensurenNeu Zensur { get; set; }
    }
}
