//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchulterminNeu : TerminNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchulterminNeu()
        {
            this.BetroffeneLerngruppen = new HashSet<BetroffeneLerngruppeNeu>();
        }
    
        public int SchuljahrId { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual SchuljahrNeu Schuljahr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetroffeneLerngruppeNeu> BetroffeneLerngruppen { get; set; }
    }
}
