//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchülereinträgeNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchülereinträgeNeu()
        {
            this.Ergebnisse = new HashSet<ErgebnisseNeu>();
            this.Hausaufgaben = new HashSet<HausaufgabenNeu>();
            this.Noten = new HashSet<NotenNeu>();
            this.Sitzplaneinträge = new HashSet<SitzplaneintragNeu>();
            this.Notentendenzen = new HashSet<NotentendenzenNeu>();
        }
    
        public int Id { get; set; }
        public int SchülerlisteId { get; set; }
        public int PersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErgebnisseNeu> Ergebnisse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HausaufgabenNeu> Hausaufgaben { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotenNeu> Noten { get; set; }
        public virtual PersonenNeu Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitzplaneintragNeu> Sitzplaneinträge { get; set; }
        public virtual SchülerlistenNeu Schülerliste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotentendenzenNeu> Notentendenzen { get; set; }
    }
}
