//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchülerlistenNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchülerlistenNeu()
        {
            this.Schülereinträge = new HashSet<SchülereinträgeNeu>();
        }
    
        public int Id { get; set; }
        public int SchuljahrId { get; set; }
        public int Halbjahr { get; set; }
        public string Bezeichnung { get; set; }
        public int FachId { get; set; }
        public int NotenWichtungId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchülereinträgeNeu> Schülereinträge { get; set; }
    }
}
