//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchülereintragNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchülereintragNeu()
        {
            this.Ergebnisse = new HashSet<ErgebnisNeu>();
            this.Hausaufgaben = new HashSet<HausaufgabeNeu>();
            this.Noten = new HashSet<NoteNeu>();
            this.Notentendenzen = new HashSet<NotentendenzNeu>();
            this.Sitzplaneinträge = new HashSet<SitzplaneintragNeu>();
        }
    
        public int Id { get; set; }
        public int LerngruppeId { get; set; }
        public int PersonId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErgebnisNeu> Ergebnisse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HausaufgabeNeu> Hausaufgaben { get; set; }
        public virtual LerngruppeNeu Lerngruppe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteNeu> Noten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotentendenzNeu> Notentendenzen { get; set; }
        public virtual PersonNeu Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitzplaneintragNeu> Sitzplaneinträge { get; set; }
    }
}
