//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SequenzenNeu
    {
        public int Id { get; set; }
        public int ReiheId { get; set; }
        public int Reihenfolge { get; set; }
        public int Stundenbedarf { get; set; }
        public string Thema { get; set; }
    
        public virtual ReihenNeu Reihe { get; set; }
    }
}
