//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitzplaneintragNeu
    {
        public int Id { get; set; }
        public int SitzplanId { get; set; }
        public int SitzplatzId { get; set; }
        public Nullable<int> SchülereintragId { get; set; }
    
        public virtual SitzplanNeu Sitzplan { get; set; }
        public virtual SitzplatzNeu Sitzplatz { get; set; }
        public virtual SchülereintragNeu Schülereintrag { get; set; }
    }
}
