//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StundeNeu : LerngruppenterminNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StundeNeu()
        {
            this.Dateiverweise = new HashSet<DateiverweisNeu>();
            this.Phasen = new HashSet<PhaseNeu>();
        }
    
        public bool IstBenotet { get; set; }
        public int FachId { get; set; }
        public int Jahrgang { get; set; }
        public Nullable<int> ModulId { get; set; }
        public bool Kopieren { get; set; }
        public bool Computer { get; set; }
        public string Hausaufgaben { get; set; }
        public string Ansagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DateiverweisNeu> Dateiverweise { get; set; }
        public virtual FächerNeu Fach { get; set; }
        public virtual ModuleNeu Modul { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhaseNeu> Phasen { get; set; }
    }
}
