//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StundenplaneintragNeu
    {
        public int Id { get; set; }
        public int StundenplanId { get; set; }
        public int ErsteUnterrichtsstundeIndex { get; set; }
        public int LetzteUnterrichtsstundeIndex { get; set; }
        public int WochentagIndex { get; set; }
        public int FachId { get; set; }
        public int LerngruppeID { get; set; }
        public int RaumId { get; set; }
    
        public virtual FachNeu Fach { get; set; }
        public virtual LerngruppeNeu Lerngruppe { get; set; }
        public virtual RaumNeu Raum { get; set; }
        public virtual StundenplanNeu Stundenplan { get; set; }
    }
}
