//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StundenplanNeu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StundenplanNeu()
        {
            this.Stundenplaneinträge = new HashSet<StundenplaneintragNeu>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int SchuljahrID { get; set; }
        public Halbjahr Halbjahr { get; set; }
        public System.DateTime GültigAb { get; set; }
    
        public virtual SchuljahrNeu Schuljahre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StundenplaneintragNeu> Stundenplaneinträge { get; set; }
    }
}
