//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    
    public enum Termintyp : int
    {
        Klausur = 0,
        TagDerOffenenTür = 1,
        Wandertag = 2,
        Abitur = 3,
        MSA = 4,
        Unterricht = 5,
        Vertretung = 6,
        Besprechung = 7,
        Sondertermin = 8,
        Ferien = 9,
        Kursfahrt = 10,
        Klassenfahrt = 11,
        Projekttag = 12,
        Praktikum = 13,
        Geburtstag = 14,
        Veranstaltung = 15,
        PSE = 16
    }
}
