//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftTeach.Model.TeachyModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminNeu
    {
        public int Id { get; set; }
        public Termintyp Termintyp { get; set; }
        public string Beschreibung { get; set; }
        public int ErsteUnterrichtsstundeId { get; set; }
        public int LetzteUnterrichtsstundeId { get; set; }
        public string Ort { get; set; }
        public bool IstGeprüft { get; set; }
    
        public virtual UnterrichtsstundeNeu ErsteUnterrichtsstunde { get; set; }
        public virtual UnterrichtsstundeNeu LetzteUnterrichtsstunde { get; set; }
    }
}
