//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class BetroffeneKlasse
    {
        public int Id { get; set; }
        public int TerminId { get; set; }
        public int KlasseId { get; set; }
    
        public virtual Schultermin Termin { get; set; }
        public virtual Klasse Klasse { get; set; }
    }
}
