//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public Curriculum()
        {
            this.Reihen = new HashSet<Reihe>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlassenstufeId { get; set; }
        public string Bezeichnung { get; set; }
        public int JahrtypId { get; set; }
        public int HalbjahrtypId { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
        public virtual Klassenstufe Klassenstufe { get; set; }
        public virtual ICollection<Reihe> Reihen { get; set; }
        public virtual Halbjahrtyp Halbjahrtyp { get; set; }
    }
}
