//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ergebnis
    {
        public int Id { get; set; }
        public int AufgabeId { get; set; }
        public int SchülereintragId { get; set; }
        public Nullable<int> Punktzahl { get; set; }
    
        public virtual Aufgabe Aufgabe { get; set; }
        public virtual Schülereintrag Schülereintrag { get; set; }
    }
}
