//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jahresplan
    {
        public Jahresplan()
        {
            this.Halbjahrespläne = new HashSet<Halbjahresplan>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int KlasseId { get; set; }
        public int JahrtypId { get; set; }
    
        public virtual Fach Fach { get; set; }
        public virtual Klasse Klasse { get; set; }
        public virtual ICollection<Halbjahresplan> Halbjahrespläne { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
    }
}
