//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Jahrgangsstufe
    {
        public Jahrgangsstufe()
        {
            this.Stundenentwurf = new HashSet<Stundenentwurf>();
            this.Klassenstufen = new HashSet<Klassenstufe>();
            this.Module = new HashSet<Modul>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Bepunktungstyp { get; set; }
    
        public virtual ICollection<Stundenentwurf> Stundenentwurf { get; set; }
        public virtual ICollection<Klassenstufe> Klassenstufen { get; set; }
        public virtual ICollection<Modul> Module { get; set; }
    }
}
