//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Klassenstufe
    {
        public Klassenstufe()
        {
            this.Fachstundenanzahl = new HashSet<Fachstundenanzahl>();
            this.Curriculum = new HashSet<Curriculum>();
            this.Klassen = new HashSet<Klasse>();
        }
    
        public int Id { get; set; }
        public int JahrgangsstufeId { get; set; }
        public string Bezeichnung { get; set; }
    
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
        public virtual ICollection<Fachstundenanzahl> Fachstundenanzahl { get; set; }
        public virtual ICollection<Curriculum> Curriculum { get; set; }
        public virtual ICollection<Klasse> Klassen { get; set; }
    }
}
