//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Modul
    {
        public Modul()
        {
            this.Bausteine = "";
            this.Stundenentwurf = new HashSet<Stundenentwurf>();
            this.Reihen = new HashSet<Reihe>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public string Bezeichnung { get; set; }
        public int JahrgangsstufeId { get; set; }
        public string Bausteine { get; set; }
        public int Stundenbedarf { get; set; }
    
        public virtual ICollection<Stundenentwurf> Stundenentwurf { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual ICollection<Reihe> Reihen { get; set; }
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
    }
}
