//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Sequenz
    {
        public Sequenz()
        {
            this.AbfolgeIndex = -1;
        }
    
        public int Id { get; set; }
        public int ReiheId { get; set; }
        public int AbfolgeIndex { get; set; }
        public int Stundenbedarf { get; set; }
        public string Thema { get; set; }
    
        public virtual Reihe Reihe { get; set; }
    }
}
