//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Stundenplan
    {
        public Stundenplan()
        {
            this.Stundenplaneinträge = new HashSet<Stundenplaneintrag>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public int JahrtypId { get; set; }
        public int HalbjahrtypId { get; set; }
        public System.DateTime GültigAb { get; set; }
    
        public virtual Halbjahrtyp Halbjahrtyp { get; set; }
        public virtual Jahrtyp Jahrtyp { get; set; }
        public virtual ICollection<Stundenplaneintrag> Stundenplaneinträge { get; set; }
    }
}
