//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Stundenentwurf
    {
        public Stundenentwurf()
        {
            this.Phasen = new HashSet<Phase>();
            this.Stunden = new HashSet<Stunde>();
            this.Dateiverweise = new HashSet<Dateiverweis>();
        }
    
        public int Id { get; set; }
        public int FachId { get; set; }
        public int JahrgangsstufeId { get; set; }
        public int ModulId { get; set; }
        public string Stundenthema { get; set; }
        public bool Kopieren { get; set; }
        public bool Computer { get; set; }
        public string Hausaufgaben { get; set; }
        public string Ansagen { get; set; }
        public System.DateTime Datum { get; set; }
        public int Stundenzahl { get; set; }
    
        public virtual ICollection<Phase> Phasen { get; set; }
        public virtual Modul Modul { get; set; }
        public virtual Fach Fach { get; set; }
        public virtual ICollection<Stunde> Stunden { get; set; }
        public virtual Jahrgangsstufe Jahrgangsstufe { get; set; }
        public virtual ICollection<Dateiverweis> Dateiverweise { get; set; }
    }
}
