//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public partial class Termintyp
    {
        public Termintyp()
        {
            this.Termin = new HashSet<Termin>();
            this.Schultag = new HashSet<Schultag>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Kalenderfarbe { get; set; }
    
        public virtual ICollection<Termin> Termin { get; set; }
        public virtual ICollection<Schultag> Schultag { get; set; }
    }
}
