//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liduv.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
        [Serializable]
    public abstract partial class Termin
    {
        public Termin()
        {
            this.Beschreibung = "";
            this.Ort = "";
        }
    
        public int Id { get; set; }
        public int TermintypId { get; set; }
        public string Beschreibung { get; set; }
        public int ErsteUnterrichtsstundeId { get; set; }
        public int LetzteUnterrichtsstundeId { get; set; }
        public string Ort { get; set; }
        public bool IstGeprüft { get; set; }
    
        public virtual Unterrichtsstunde ErsteUnterrichtsstunde { get; set; }
        public virtual Unterrichtsstunde LetzteUnterrichtsstunde { get; set; }
        public virtual Termintyp Termintyp { get; set; }
    }
}
